workspace:
  base: /
  path: src/

pipeline:
  build:
    image: busybox
    commands:
      - pwd
      - ls
  trigger:
    branch:
    - master

  publish:
      image: plugins/docker
      registry: https://index.docker.io/v1/ # 仓库
      repo: coding365/drone-test # docker仓库地址
      # mirror: https://docker.mirrors.ustc.edu.cn
      # 需要使用drone cli添加secrets: http://docs.drone.io/manage-secrets/
      secrets: [ coding365, wyx123jdyz ]
      tags:
        - latest